stages:
  - build

build:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin <<<$CI_REGISTRY_PASSWORD
    - docker build -t gitlab.nicewhite.xyz:8443/yoni13/yulin-loves-melody .
    - docker push -t gitlab.nicewhite.xyz:8443/yoni13/yulin-loves-melody .
