services:
  - docker:24.0.5-dind
before_script:
  - docker info
stages:
  - build

build:
  stage: build
  script:
    - apk add --no-cache bash git 
    - bash -c "docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin <<<$CI_REGISTRY_PASSWORD"
    - docker build -t gitlab.nicewhite.xyz:8443/yoni13/yulin-loves-melody . --force-rm
    - docker push gitlab.nicewhite.xyz:8443/yoni13/yulin-loves-melody
