services:
  - docker:24.0.5-dind
stages:
  - build

build:
  stage: build
    variables:
      IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - apk add --no-cache git
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
